name: "Docker metadata"
description: "Provide Docker metadata (tags, labels, …)"
inputs:
  default-branch:
    description: "Name of the default Git branch"
    required: false
    default: ${{ github.event.repository.default_branch }}
  images:
    description: "Docker images"
    required: true
  strip-tag-prefix:
    description: "Strip a tag prefix"
    required: false
  include-pipeline-id:
    description: "Include a tag that contains the branch name and the pipeline ID if set to 'true'"
    required: false
outputs:
  tags: # list of tags separated using commas
    description: "List of tags"
  labels: # list of labels separated using commas
    description: "List of labels"
runs:
  using: "docker"
  image: "docker://ghcr.io/zazuko/deploy-image:v1.4"
  env:
    DEFAULT_BRANCH: ${{ inputs.default-branch }}
    DOCKER_IMAGES: ${{ inputs.images }}
    STRIP_TAG_PREFIX: ${{ inputs.strip-tag-prefix }}
    INCLUDE_PIPELINE_ID: ${{ inputs.include-pipeline-id }}
  args:
    - github-docker
